services:
  app:
    container_name: "app"
    build: .
    env_file:
      - app.env
    ports:
      - "5000:8080"
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    container_name: "mysql"
    image: "mysql:8"
    restart: "always"
    env_file:
      - db.env
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 3
  phpmyadmin:
    container_name: "phpmyadmin"
    image: "phpmyadmin/phpmyadmin"
    restart: "always"
    env_file:
      - pma.env
    ports:
      - "5001:80"
    depends_on:
      - mysql
volumes:
  db-data: